# Generated by Django 5.2.7 on 2025-10-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
