services:
  postgres:
    image: postgres:15-alpine
    container_name: project_name_postgres
    environment:
      POSTGRES_DB: project_name_db
      POSTGRES_USER: project_name_user
      POSTGRES_PASSWORD: project_name_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_name_user -d project_name_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: project_name_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: project_name_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://project_name_user:project_name_pass@postgres:5432/project_name_db
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
